# Generated by Django 4.1.6 on 2023-02-16 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0009_remove_product_sub_category_delete_subcategory'),
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AddField(
            model_name='action',
            name='product',
            field=models.ManyToManyField(to='app_shop.product', verbose_name='Привязка к продукту:'),
        ),
        migrations.AddField(
            model_name='action',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название акции: '),
        ),
    ]
