# Generated by Django 4.1.6 on 2023-02-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_alter_action_options_action_product_action_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='in_stock',
            field=models.IntegerField(default=0, verbose_name='Количество:'),
        ),
    ]
